### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by lowderdev** [bitwalker/distillery-test#9]
After running the first half of the command from the README I get this response from ping:

```
llowder: /tmp/test$ cd /tmp/test && tar -xf test.tar.gz && ./bin/test start
[
  {:debug_level, {:on, [:passive]}},
  {:namespace, Web},
  {:username, nil},
  {:source, "/private/tmp/test/etc/config.exs"},
  {:env, nil},
  {TestWeb.Endpoint,
   [
     render_errors: [view: TestWeb.ErrorView, accepts: ["html", "json"]],
     pubsub: [name: Test.PubSub, adapter: Phoenix.PubSub.PG2],
     debug_errors: true,
     code_reloader: true,
     check_origin: false,
     watchers: [
       node: [
         "node_modules/brunch/bin/brunch",
         "watch",
         "--stdin",
         {:cd, "/Users/llowder/workspace/distillery-test/assets"}
       ]
     ],
     live_reload: [
       patterns: [~r/priv\/static\/.*(js|css|png|jpeg|jpg|gif|svg)$/,
        ~r/priv\/gettext\/.*(po)$/, ~r/lib\/test_web\/views\/.*(ex)$/,
        ~r/lib\/test_web\/templates\/.*(eex)$/]
     ],
     server: true,
     load_from_system_env: false,
     http: [port: 4000],
     url: [host: "localhost", port: 4000],
     root: ".",
     secret_key_base: "u1QXlca4XEZKb1o3HL/aUlznI1qstCNAQ6yme/lFbFIs0Iqiq/annZ+Ty8JyUCDc"
   ]}
]
llowder: /tmp/test$ ./bin/test ping
▸  Received 'pang' from test@127.0.0.1!
▸  Possible reasons for this include:
▸    - The cookie is mismatched between us and the target node
▸    - We cannot establish a remote connection to the node
```

If I run `./bin/test_rc_exec.sh foreground` I see the following:

```
llowder: /tmp/test$ ./bin/test_rc_exec.sh foreground
[
  {:debug_level, {:on, [:passive]}},
  {:namespace, Web},
  {:username, nil},
  {:source, "/private/tmp/test/etc/config.exs"},
  {:env, nil},
  {TestWeb.Endpoint,
   [
     render_errors: [view: TestWeb.ErrorView, accepts: ["html", "json"]],
     pubsub: [name: Test.PubSub, adapter: Phoenix.PubSub.PG2],
     debug_errors: true,
     code_reloader: true,
     check_origin: false,
     watchers: [
       node: [
         "node_modules/brunch/bin/brunch",
         "watch",
         "--stdin",
         {:cd, "/Users/llowder/workspace/distillery-test/assets"}
       ]
     ],
     live_reload: [
       patterns: [~r/priv\/static\/.*(js|css|png|jpeg|jpg|gif|svg)$/,
        ~r/priv\/gettext\/.*(po)$/, ~r/lib\/test_web\/views\/.*(ex)$/,
        ~r/lib\/test_web\/templates\/.*(eex)$/]
     ],
     server: true,
     load_from_system_env: false,
     http: [port: 4000],
     url: [host: "localhost", port: 4000],
     root: ".",
     secret_key_base: "u1QXlca4XEZKb1o3HL/aUlznI1qstCNAQ6yme/lFbFIs0Iqiq/annZ+Ty8JyUCDc"
   ]}
]
[error] GenServer Phoenix.CodeReloader.Server terminating
** (stop) exited in: GenServer.call(Mix.ProjectStack, {:get, #Function<11.5643525/1 in Mix.ProjectStack.peek/0>}, 30000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:979: GenServer.call/3
    (mix) lib/mix/project.ex:192: Mix.Project.config/0
    (mix) lib/mix/project.ex:235: Mix.Project.umbrella?/0
    (phoenix) lib/phoenix/code_reloader/server.ex:27: Phoenix.CodeReloader.Server.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from TestWeb.Endpoint): :check_symlinks
State: false
Client TestWeb.Endpoint is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:986: GenServer.call/3
    (phoenix) lib/phoenix/endpoint/supervisor.ex:62: Phoenix.Endpoint.Supervisor.init/1
    (stdlib) supervisor.erl:295: :supervisor.init/1
    (stdlib) gen_server.erl:374: :gen_server.init_it/2
    (stdlib) gen_server.erl:342: :gen_server.init_it/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
[info] Application test exited: Test.Application.start(:normal, []) returned an error: shutdown: failed to start child: TestWeb.Endpoint
    ** (EXIT) exited in: GenServer.call(Phoenix.CodeReloader.Server, :check_symlinks, :infinity)
        ** (EXIT) exited in: GenServer.call(Mix.ProjectStack, {:get, #Function<11.5643525/1 in Mix.ProjectStack.peek/0>}, 30000)
            ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
{"Kernel pid terminated",application_controller,"{application_start_failure,test,{{shutdown,{failed_to_start_child,'Elixir.TestWeb.Endpoint',{{noproc,{'Elixir.GenServer',call,['Elixir.Mix.ProjectStack',{get,#Fun<Elixir.Mix.ProjectStack.11.5643525>},30000]}},{'Elixir.GenServer',call,['Elixir.Phoenix.CodeReloader.Server',check_symlinks,infinity]}}}},{'Elixir.Test.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,test,{{shutdown,{failed_to_start_child,'Elixir.TestWeb.Endpoint',{{noproc,{'Elixir.GenServer',call,['Elixir.Mix.ProjectStack'

Crash dump is being written to: erl_crash.dump...done
```

Figured I should provide this:

```
llowder: /tmp/test$ elixir -v
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

**Comment by lowderdev** [comment]
Do I need to specify elixir 1.8 in my `mix.exs`?

**Comment by gmanolache** [comment]
I'm having the same issue
